"""empty message

Revision ID: 1663e32cc8e7
Revises: 10a2f103d90a
Create Date: 2015-09-16 12:44:59.737000

"""

# revision identifiers, used by Alembic.
revision = '1663e32cc8e7'
down_revision = '10a2f103d90a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
