"""empty message

Revision ID: 1bb717bb920e
Revises: 1663e32cc8e7
Create Date: 2015-09-16 16:27:25.220000

"""

# revision identifiers, used by Alembic.
revision = '1bb717bb920e'
down_revision = '1663e32cc8e7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
